language: python
sudo: false
dist: xenial
python:
- 3.6
- 3.7
- 3.8
install:
- pip install -e .[testing]
script: pytest tests
deploy:
  provider: pypi
  user: vmalloc
  password:
    secure: IiRY8I5mIBebKxMUNygddVLyyd0j9gRG5hly5r07nIeqqB01cUhrHgTnfqQPBbVYsDzFYRNM4p2+D94YlsRyO/ylGXehNpA/Dmb5tVDLtycbQVBx4rkRwEa0nfcXaF3MO1P0NHbEi3scVhLiaYqTGWsEKGIhUrgWyckuAh99FKo=
  on:
    tags: true
    repo: getslash/flux
